/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SekaniTravyRouteImport } from './routes/sekani-travy'
import { Route as SekaniSvahuRouteImport } from './routes/sekani-svahu'
import { Route as RizikoveKaceniRouteImport } from './routes/rizikove-kaceni'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as MulcovaniNaletuRouteImport } from './routes/mulcovani-naletu'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SekaniTravyRoute = SekaniTravyRouteImport.update({
  id: '/sekani-travy',
  path: '/sekani-travy',
  getParentRoute: () => rootRouteImport,
} as any)
const SekaniSvahuRoute = SekaniSvahuRouteImport.update({
  id: '/sekani-svahu',
  path: '/sekani-svahu',
  getParentRoute: () => rootRouteImport,
} as any)
const RizikoveKaceniRoute = RizikoveKaceniRouteImport.update({
  id: '/rizikove-kaceni',
  path: '/rizikove-kaceni',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const MulcovaniNaletuRoute = MulcovaniNaletuRouteImport.update({
  id: '/mulcovani-naletu',
  path: '/mulcovani-naletu',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kontakt': typeof KontaktRoute
  '/mulcovani-naletu': typeof MulcovaniNaletuRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/reference': typeof ReferenceRoute
  '/rizikove-kaceni': typeof RizikoveKaceniRoute
  '/sekani-svahu': typeof SekaniSvahuRoute
  '/sekani-travy': typeof SekaniTravyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kontakt': typeof KontaktRoute
  '/mulcovani-naletu': typeof MulcovaniNaletuRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/reference': typeof ReferenceRoute
  '/rizikove-kaceni': typeof RizikoveKaceniRoute
  '/sekani-svahu': typeof SekaniSvahuRoute
  '/sekani-travy': typeof SekaniTravyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/kontakt': typeof KontaktRoute
  '/mulcovani-naletu': typeof MulcovaniNaletuRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
  '/reference': typeof ReferenceRoute
  '/rizikove-kaceni': typeof RizikoveKaceniRoute
  '/sekani-svahu': typeof SekaniSvahuRoute
  '/sekani-travy': typeof SekaniTravyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cenik'
    | '/kontakt'
    | '/mulcovani-naletu'
    | '/ochrana-osobnich-udaju'
    | '/reference'
    | '/rizikove-kaceni'
    | '/sekani-svahu'
    | '/sekani-travy'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenik'
    | '/kontakt'
    | '/mulcovani-naletu'
    | '/ochrana-osobnich-udaju'
    | '/reference'
    | '/rizikove-kaceni'
    | '/sekani-svahu'
    | '/sekani-travy'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/cenik'
    | '/kontakt'
    | '/mulcovani-naletu'
    | '/ochrana-osobnich-udaju'
    | '/reference'
    | '/rizikove-kaceni'
    | '/sekani-svahu'
    | '/sekani-travy'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenikRoute: typeof CenikRoute
  KontaktRoute: typeof KontaktRoute
  MulcovaniNaletuRoute: typeof MulcovaniNaletuRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
  ReferenceRoute: typeof ReferenceRoute
  RizikoveKaceniRoute: typeof RizikoveKaceniRoute
  SekaniSvahuRoute: typeof SekaniSvahuRoute
  SekaniTravyRoute: typeof SekaniTravyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekani-travy': {
      id: '/sekani-travy'
      path: '/sekani-travy'
      fullPath: '/sekani-travy'
      preLoaderRoute: typeof SekaniTravyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sekani-svahu': {
      id: '/sekani-svahu'
      path: '/sekani-svahu'
      fullPath: '/sekani-svahu'
      preLoaderRoute: typeof SekaniSvahuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rizikove-kaceni': {
      id: '/rizikove-kaceni'
      path: '/rizikove-kaceni'
      fullPath: '/rizikove-kaceni'
      preLoaderRoute: typeof RizikoveKaceniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulcovani-naletu': {
      id: '/mulcovani-naletu'
      path: '/mulcovani-naletu'
      fullPath: '/mulcovani-naletu'
      preLoaderRoute: typeof MulcovaniNaletuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenikRoute: CenikRoute,
  KontaktRoute: KontaktRoute,
  MulcovaniNaletuRoute: MulcovaniNaletuRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
  ReferenceRoute: ReferenceRoute,
  RizikoveKaceniRoute: RizikoveKaceniRoute,
  SekaniSvahuRoute: SekaniSvahuRoute,
  SekaniTravyRoute: SekaniTravyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
